Add tekton core type and Output component integration utils
redhat-developer/aonic-ui pull request #16
Opened 2024-02-08 16:44 UTC by karthikjeeyar

This PR contains the following changes

1. Add Tekton core types.
2. Add output integration utils, hooks and unit tests.
3. Add sample data helper utility to compose pipelinerun, taskruns and pods.
4. Add tech documentation and update readme.

2024-02-12 17:13 UTC, rohitkrai03 requested changes

2024-02-12 17:13 UTC, rohitkrai03 commented on packages/pipelines/src/components/Output/hooks/usePipelineRunOutput.ts
> +  return {
Use `React.useMemo` here?

2024-02-13 05:21 UTC, karthikjeeyar commented on packages/pipelines/src/components/Output/hooks/usePipelineRunOutput.ts
> +  return {
Updated.

2024-02-13 07:11 UTC, rohitkrai03 approved these changes
/lgtm
/approve

2024-02-13 07:23 UTC, merged